nelmio_api_doc:
    documentation:
        info:
            title: 'Task API'
            description: 'API Rest pour la gestion des tâches'
            version: '1.0.0'
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/api(?!/doc$)